log:
  filePath: "/var/log/traefik/traefik.log"
  level: INFO

api:
  insecure: true
  dashboard: false

providers:
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

entryPoints:
  web:
    address: ":80"
