global:
  scrape_interval: 15s      #Scrape interval to every 15 seconds.
  evaluation_interval: 15s  #Evaluate rules every 15 seconds.
  
scrape_configs:
  - job_name: pgsql
    static_configs:
      - targets: ["pgqsl_exporter:9187"]

  - job_name: application
    static_configs:
      - targets: ["application:8080"]